name: Publish Quarto Document to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'pages.qmd'
      - 'references.bib'
      - 'pages_files/**'

jobs:
  quarto-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.450
      
      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@v2
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
  
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbformat pandas matplotlib seaborn datasets
      
      - name: Render Quarto Document
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: pages.qmd
          to: html
          
      - name: Create _site directory and move rendered files
        run: |
          mkdir -p _site
          cp pages.html _site/index.html
          cp -r pages_files _site/ || true
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
          branch: gh-pages